version: "3.8"

services:
  INAME:
    image: INAME
    privileged: true
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DOCKERIZED=true
    restart: always
    volumes:
      - .:/app
      - ~/.application/empty:/app/node_modules
